import Config

# Configure your database
# TODO: learn how to properly configure a database cerficate
# IMPORTANT: that certificate cannot be stored on the repo
config :phoenix_test, PhoenixTest.Repo,
  ssl: true,
  pool_size: 10,
  ssl_opts: [
    verify: :verify_none
  ]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :phoenix_test, PhoenixTestWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PhoenixTest.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
